# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: FlutterInstall@0
  inputs:
    channel: 'stable'
    version: 'latest'

- task: FlutterCommand@0
  inputs:
    arguments: 'build web --release'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/build'
    ArtifactName: 'flutterWeb'
    publishLocation: 'Container'

