name: scrapmechanic_kurtlourens_com
description: A companion app for Scrap Mechanic.
publish_to: 'none'
version: 1.1.9+30

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3

  # Firebase
  firebase_core: 0.5.0
  firebase_analytics: 6.0.0
  firebase_analytics_web: ^0.1.1
  # Redux
  flutter_redux: 0.6.0
  redux: 4.0.0+3
  # UI
  badges: ^1.1.3
  theme_mode_handler: ^2.0.0
  rflutter_alert: ^1.1.0
  flutter_staggered_grid_view: ^0.3.2
  country_icons: ^1.1.1
  step_progress_indicator: ^0.2.4+7
  flash: "^1.3.1" # Snackbar
  giffy_dialog: ^1.8.0
  dotted_border: ^1.0.6
  grouped_checkbox: ^1.0.0
  ff_navigation_bar: ^0.1.5
  # Base
  get_it: ^5.0.1
  http: ^0.12.2
  uuid: ^2.2.2
  dartx: ^0.5.0
  fluro: ^1.6.3
  logger: ^0.9.4
  shared_preferences: ^0.5.12
  shared_preferences_web: ^0.1.2+7
  # Misc
  url_launcher: ^5.7.2
  url_launcher_web: ^0.1.4+1
  package_info: ^0.4.3
  enum_to_string: ^1.0.13
  share: ^0.6.5+2
  universal_html: ^1.2.3
  universal_platform: ^0.1.3
  breakpoint: ^1.0.1+2
  after_layout: ^1.0.7+2

dev_dependencies:
  flutter_launcher_icons: "^0.8.0"
  # flutter_test:
  #   sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path: "assets/img/fullSizeIcon.png"
  adaptive_icon_background: "assets/img/fullSizeIconAdaptiveBg.png"
  adaptive_icon_foreground: "assets/img/fullSizeIconAdaptiveFg.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/data/ # Data files
    - assets/lang/ # Languages
    
    # Images
    - assets/img/ 
    - assets/img/donation/
    - assets/img/drawer/
    - assets/img/items/
    - assets/img/raid/
    - assets/img/rating/dark/
    - assets/img/rating/light/
    - assets/img/tile/

    # Base Json Items
    - assets/json/ 
    - assets/json/de/
    - assets/json/en/
    - assets/json/es/
    - assets/json/fr/
    - assets/json/it/
    - assets/json/ja/
    - assets/json/ko/
    - assets/json/po/
    - assets/json/pt-br/
    - assets/json/ru/
    - assets/json/zh-hans/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
